### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by groundedsage** [clojure-quant/trateg#6]
When I follow the documentation from a fresh clone of the repository it does not work. I believe the documentation is out of sync.

**Comment by awb99** [comment]
Unfortunately you are correct. 
I made the switch to use tech.ml dataset; which allows to usebit wirh big data.
This switch is not yet 100% complete;  and I  am currently actively adding new features.

However the project works and I use it daily. 
We could do a session (teamviewer,...)  to get  you stated.
In a few weeks when I finish the refactorings I will add better documentation.

**Comment by groundedsage** [comment]
A session would be great. I've been working on my own minimal implementation and it would be nice to be able to merge efforts as a lot of the libraries and decisions are the same. Send me a message on Clojurians and let's organise a time.

**Comment by awb99** [comment]
Documentation improved to get demo to run.
